
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - helm.watcher
  resources:
  - helmrepositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - helm.watcher
  resources:
  - helmrepositories/status
  verbs:
  - get
